include:
  - project: 'dev-ops/ci'
    file:
      - '/hubci.yml'

stages:
  - test
  - build
  - deploy

default:
  image: python:3.9
  before_script:
    - pip install poetry
    - poetry install
    - source `poetry env info --path`/bin/activate


test:
  stage: test
  script:
    - poetry run pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml

build:
  stage: build
  script:
    - poetry build
  artifacts:
    expire_in: 30 days
    paths:
      - dist/

deploy:
  stage: deploy
  script:
    - poetry config repositories.gitlab "$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/packages/pypi"
    - poetry config http-basic.gitlab gitlab-ci-token "$CI_JOB_TOKEN"
    - poetry publish --repository gitlab
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'