name: Test
on:
  pull_request:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v2.2.1
      with:
        python-version: '3.8'
    - name: Install Poetry
      uses: dschep/install-poetry-action@v1.3
      with:
        version: 1.1.4
    - name: Install Dependencies
      run: poetry install
    - name: Test
      run: pytest
