name: Tests
on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        poetry-version: [1.1.4]
        os: [ubuntu-20.04]

    steps:
    - uses: actions/checkout@v1

    - name: Setup Python
      uses: actions/setup-python@v2.2.1
      with:
        python-version: '3.8'

    - name: Setup Poetry
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: ${{ matrix.poetry-version }}

    - name: Install Dependencies
      run: poetry install

    - name: Test
      run: poetry run pytest
